### ISSUE TITLE
Exception on background Image

### ISSUE THREAD

**Issue by ExaMuff** [markn86/moodle-mod_customcert#117]
Hi,
the plugin thrown an Exception adding a Background Image

Moodle 3.1

Call to a member function get_contextid() on boolean
Error code: generalexceptionmessage
Stack trace:

    line 150 of /mod/customcert/element/image/classes/element.php: Error thrown
    line 130 of /mod/customcert/classes/element.php: call to customcertelement_image\element->save_unique_data()
    line 135 of /mod/customcert/element/image/classes/element.php: call to mod_customcert\element->save_form_elements()
    line 90 of /mod/customcert/edit_element.php: call to customcertelement_image\element->save_form_elements()

**Comment by markn86** [comment]
Hmm, seems like the image was not found during the upgrade to the latest release so was not converted. What happens if you re-select the background image and save the form?

**Comment by markn86** [comment]
Ah, was able to replicate this!

**Comment by markn86** [comment]
This happens when you have 'No image' selected in the 'Image' drop down.

**Comment by markn86** [comment]
Fixed. :)

**Comment by relecand** [comment]
Hi Mark,

this error still exists in the M3.1 branch.

All the best,

Christian

**Comment by markn86** [comment]
Hi @relecand, 3.1 was not supported so this wasn't backported. However, I've changed my mind about not supporting it as I have seen a lot of sites still using that version. So, on the weekend I plan on backporting all changes and pushing a new version.
